// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmOtwvhyB9VWj86zc6m4tD7PDVJEZM5X8',
    appId: '1:953227686629:android:355a5af256c854132c1a0c',
    messagingSenderId: '953227686629',
    projectId: 'connect-ab',
    storageBucket: 'connect-ab.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATRpbz85735FUGJgcPKecyhoj1gkIJWj0',
    appId: '1:953227686629:web:12eabeeedc0219722c1a0c',
    messagingSenderId: '953227686629',
    projectId: 'connect-ab',
    authDomain: 'connect-ab.firebaseapp.com',
    storageBucket: 'connect-ab.firebasestorage.app',
    measurementId: 'G-T26BEZLWXF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpcIhbYwozwPoBHN-fpbSPIvhe1y-cMDo',
    appId: '1:953227686629:ios:a55616affc2fe50f2c1a0c',
    messagingSenderId: '953227686629',
    projectId: 'connect-ab',
    storageBucket: 'connect-ab.firebasestorage.app',
    iosBundleId: 'com.example.bassamAb',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpcIhbYwozwPoBHN-fpbSPIvhe1y-cMDo',
    appId: '1:953227686629:ios:a55616affc2fe50f2c1a0c',
    messagingSenderId: '953227686629',
    projectId: 'connect-ab',
    storageBucket: 'connect-ab.firebasestorage.app',
    iosBundleId: 'com.example.bassamAb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATRpbz85735FUGJgcPKecyhoj1gkIJWj0',
    appId: '1:953227686629:web:1ed419629a9d08ec2c1a0c',
    messagingSenderId: '953227686629',
    projectId: 'connect-ab',
    authDomain: 'connect-ab.firebaseapp.com',
    storageBucket: 'connect-ab.firebasestorage.app',
    measurementId: 'G-QJCFCB21YY',
  );
}
